

// "use client";

// import { useMemo, useState } from "react";
// import { FormProvider, useForm } from "react-hook-form";
// import { zodResolver } from "@hookform/resolvers/zod";
// import { HiOutlineXMark } from "react-icons/hi2";

// import { buildPropertyPayload, slugifyPropertyTitle } from "@/lib/utils/property";
// import { uploadPropertyFiles } from "@/lib/storage/upload-property-files";
// import PropertyFormFields from "./PropertyFormFields";
// import FilePicker from "./FilePicker";
// import SectionCard from "./SectionCard";
// import { propertyFormSchema, PropertyFormValues } from "@/lib/validators/property-form";

// type AddPropertyModalProps = {
//   isOpen: boolean;
//   onClose: () => void;
// };

// const defaultValues: PropertyFormValues = {
//   title: "",
//   kind: "HOUSE",
//   purpose: "SELL",
//   marketType: "ON_MARKET",
//   rentType: "",
//   priceAmount: "",
//   priceCurrency: "RWF",
//   pricePeriod: "",
//   priceOnApplication: false,
//   description: "",

//   country: "Rwanda",
//   city: "Kigali",
//   province: "",
//   district: "",
//   sector: "",
//   cell: "",
//   village: "",
//   lat: "",
//   lng: "",

//   highlights: [],

//   bedrooms: "",
//   bathrooms: "",
//   sizeSqm: "",
//   furnished: "",
//   amenities: [],

//   plotSizeSqm: "",
//   zoning: "",
//   titleType: "",
//   titleStatus: "",
//   accessRoad: "",
//   water: false,
//   electricity: false,
//   internetFiber: false,
//   sewage: false,
//   surveyAvailable: false,
//   boundariesMarked: false,
//   restrictions: [],
// };

// export default function AddPropertyModal({
//   isOpen,
//   onClose,
// }: AddPropertyModalProps) {
//   const methods = useForm<PropertyFormValues>({
//     resolver: zodResolver(propertyFormSchema),
//     defaultValues,
//     mode: "onSubmit",
//   });

//   const [galleryFiles, setGalleryFiles] = useState<File[]>([]);
//   const [videoFiles, setVideoFiles] = useState<File[]>([]);
//   const [submitError, setSubmitError] = useState("");
//   const [submitting, setSubmitting] = useState(false);

// //   const title = methods.watch("title");
// const title = methods.watch("title") ?? "";
// //   const slug = useMemo(() => slugifyPropertyTitle(title), [title]);
// const slug = useMemo(() => slugifyPropertyTitle(title), [title]);

//   if (!isOpen) return null;

//   const handleClose = () => {
//     if (submitting) return;
//     methods.reset(defaultValues);
//     setGalleryFiles([]);
//     setVideoFiles([]);
//     setSubmitError("");
//     onClose();
//   };

//   const onSubmit = methods.handleSubmit(async (values) => {
//     setSubmitError("");

//     if (galleryFiles.length === 0) {
//       setSubmitError("Please add at least one gallery image.");
//       return;
//     }

//     try {
//       setSubmitting(true);

//       const { galleryMedia, videoMedia } = await uploadPropertyFiles({
//         bucket: "property-media",
//         slug,
//         galleryFiles,
//         videoFiles,
//       });

//       const payload = buildPropertyPayload({
//         values,
//         slug,
//         galleryMedia,
//         videoMedia,
//       });

//       const response = await fetch("/api/admin/properties/create", {
//         method: "POST",
//         headers: {
//           "Content-Type": "application/json",
//         },
//         body: JSON.stringify(payload),
//       });

//       const result = await response.json();

//       if (!response.ok) {
//         throw new Error(result?.error || "Failed to save property.");
//       }

//       handleClose();
//     } catch (error) {
//       setSubmitError(
//         error instanceof Error ? error.message : "Failed to save property."
//       );
//     } finally {
//       setSubmitting(false);
//     }
//   });

//   return (
//     <div className="fixed inset-0 z-[99999] flex items-center justify-center bg-black/50 p-4">
//       <div className="max-h-[95vh] w-full max-w-6xl overflow-hidden rounded-[28px] border border-neutral-200 bg-[#F6F7FB] shadow-2xl">
//         <div className="flex items-center justify-between border-b border-neutral-100 bg-white p-5">
//           <div>
//             <h2 className="text-2xl font-bold text-black">Add Property</h2>
//             <p className="mt-1 text-sm text-neutral-500">
//               Files only for gallery and videos. Slug is auto-generated by the system.
//             </p>
//           </div>

//           <button
//             type="button"
//             onClick={handleClose}
//             className="inline-flex h-11 w-11 items-center justify-center rounded-2xl border border-neutral-200 bg-white text-neutral-600 transition hover:border-black hover:text-black"
//           >
//             <HiOutlineXMark className="text-2xl" />
//           </button>
//         </div>

//         <FormProvider {...methods}>
//           <form
//             onSubmit={onSubmit}
//             className="max-h-[calc(95vh-88px)] space-y-6 overflow-y-auto p-5"
//           >
//             {submitError ? (
//               <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
//                 {submitError}
//               </div>
//             ) : null}

//             <PropertyFormFields slugPreview={slug || "auto-generated"} />

//             <SectionCard
//               title="Gallery"
//               subtitle="Gallery accepts image files only. External links are not allowed."
//             >
//               <FilePicker
//                 label="Gallery Images"
//                 accept="image/png,image/jpeg,image/jpg,image/webp"
//                 multiple
//                 files={galleryFiles}
//                 onChange={setGalleryFiles}
//                 helperText="Accepted: PNG, JPG, JPEG, WEBP"
//               />
//             </SectionCard>

//             <SectionCard
//               title="Videos"
//               subtitle="Videos accept file uploads only. External links are not allowed."
//             >
//               <FilePicker
//                 label="Video Files"
//                 accept="video/mp4,video/webm,video/quicktime"
//                 multiple
//                 files={videoFiles}
//                 onChange={setVideoFiles}
//                 helperText="Accepted: MP4, WEBM, MOV"
//               />
//             </SectionCard>

//             <div className="flex flex-col-reverse gap-3 border-t border-neutral-100 pt-6 sm:flex-row sm:justify-end">
//               <button
//                 type="button"
//                 onClick={handleClose}
//                 disabled={submitting}
//                 className="inline-flex h-12 items-center justify-center rounded-2xl border border-neutral-200 bg-white px-5 text-sm font-semibold text-black transition hover:border-black disabled:opacity-60"
//               >
//                 Cancel
//               </button>

//               <button
//                 type="submit"
//                 disabled={submitting}
//                 className="inline-flex h-12 items-center justify-center rounded-2xl bg-black px-5 text-sm font-semibold text-white transition hover:opacity-90 disabled:opacity-60"
//               >
//                 {submitting ? "Saving..." : "Save Property"}
//               </button>
//             </div>
//           </form>
//         </FormProvider>
//       </div>
//     </div>
//   );
// }

"use client";

import { useMemo, useState } from "react";
import { FormProvider, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { HiOutlineXMark } from "react-icons/hi2";
// import {
//   propertyFormSchema,
//   type PropertyFormValues,
// } from "@/lib/validation/property-form";
import { buildPropertyPayload, slugifyPropertyTitle } from "@/lib/utils/property";
import { uploadPropertyFiles } from "@/lib/storage/upload-property-files";
import PropertyFormFields from "./PropertyFormFields";
import FilePicker from "./FilePicker";
import SectionCard from "./SectionCard";
import { propertyFormSchema, PropertyFormValues } from "@/lib/validators/property-form";

type AddPropertyModalProps = {
  isOpen: boolean;
  onClose: () => void;
};

const defaultValues: PropertyFormValues = {
  title: "",
  kind: "HOUSE",
  purpose: "SELL",
  marketType: "ON_MARKET",
  rentType: "",
  priceAmount: "",
  priceCurrency: "RWF",
  pricePeriod: "",
  priceOnApplication: false,
  description: "",

  country: "Rwanda",
  city: "Kigali",
  province: "",
  district: "",
  sector: "",
  cell: "",
  village: "",
  lat: "",
  lng: "",

  highlights: [],

  bedrooms: "",
  bathrooms: "",
  sizeSqm: "",
  furnished: "",
  amenities: [],

  plotSizeSqm: "",
  zoning: "",
  titleType: "",
  titleStatus: "",
  accessRoad: "",
  water: false,
  electricity: false,
  internetFiber: false,
  sewage: false,
  surveyAvailable: false,
  boundariesMarked: false,
  restrictions: [],
};

export default function AddPropertyModal({
  isOpen,
  onClose,
}: AddPropertyModalProps) {
  const methods = useForm<PropertyFormValues>({
    resolver: zodResolver(propertyFormSchema),
    defaultValues,
    mode: "onSubmit",
  });

  const [galleryFiles, setGalleryFiles] = useState<File[]>([]);
  const [videoFiles, setVideoFiles] = useState<File[]>([]);
  const [submitError, setSubmitError] = useState("");
  const [submitSuccess, setSubmitSuccess] = useState("");
  const [debugMessage, setDebugMessage] = useState("");
  const [submitting, setSubmitting] = useState(false);

  const title = methods.watch("title") ?? "";
  const slug = useMemo(() => slugifyPropertyTitle(title), [title]);

  if (!isOpen) return null;

  const resetState = () => {
    methods.reset(defaultValues);
    setGalleryFiles([]);
    setVideoFiles([]);
    setSubmitError("");
    setSubmitSuccess("");
    setDebugMessage("");
  };

  const handleClose = () => {
    if (submitting) return;
    resetState();
    onClose();
  };

  const onSubmit = methods.handleSubmit(async (values) => {
    setSubmitError("");
    setSubmitSuccess("");
    setDebugMessage("");

    if (!slug) {
      setSubmitError("Slug could not be generated. Please add a valid title.");
      return;
    }

    if (galleryFiles.length === 0) {
      setSubmitError("Please add at least one gallery image.");
      return;
    }

    try {
      setSubmitting(true);
      setDebugMessage("Uploading media files...");

      const { galleryMedia, videoMedia } = await uploadPropertyFiles({
        bucket: "property-media",
        slug,
        galleryFiles,
        videoFiles,
      });

      setDebugMessage("Media uploaded. Preparing property payload...");

      const payload = buildPropertyPayload({
        values,
        slug,
        galleryMedia,
        videoMedia,
      });

      setDebugMessage("Saving property to database...");

      const response = await fetch("/api/admin/properties/create", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result?.error || "Failed to save property to database.");
      }

      setSubmitSuccess("Property saved successfully into database.");
      setDebugMessage(`Saved property ID: ${result?.property?.id ?? "unknown"}`);

      resetState();

      setTimeout(() => {
        onClose();
      }, 1200);
    } catch (error) {
      console.error("Save property error:", error);
      setSubmitError(
        error instanceof Error ? error.message : "Failed to save property."
      );
      setDebugMessage("The save flow stopped before completion.");
    } finally {
      setSubmitting(false);
    }
  });

  return (
    <div className="fixed inset-0 z-[99999] flex items-center justify-center bg-black/50 p-4">
      <div className="max-h-[95vh] w-full max-w-6xl overflow-hidden rounded-[28px] border border-neutral-200 bg-[#F6F7FB] shadow-2xl">
        <div className="flex items-center justify-between border-b border-neutral-100 bg-white p-5">
          <div>
            <h2 className="text-2xl font-bold text-black">Add Property</h2>
            <p className="mt-1 text-sm text-neutral-500">
              Upload gallery and video files, then save property to database.
            </p>
          </div>

          <button
            type="button"
            onClick={handleClose}
            className="inline-flex h-11 w-11 items-center justify-center rounded-2xl border border-neutral-200 bg-white text-neutral-600 transition hover:border-black hover:text-black"
          >
            <HiOutlineXMark className="text-2xl" />
          </button>
        </div>

        <FormProvider {...methods}>
          <form
            onSubmit={onSubmit}
            className="max-h-[calc(95vh-88px)] space-y-6 overflow-y-auto p-5"
          >
            {submitError ? (
              <div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
                {submitError}
              </div>
            ) : null}

            {submitSuccess ? (
              <div className="rounded-2xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-700">
                {submitSuccess}
              </div>
            ) : null}

            {debugMessage ? (
              <div className="rounded-2xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-700">
                {debugMessage}
              </div>
            ) : null}

            <PropertyFormFields slugPreview={slug || "auto-generated"} />

            <SectionCard
              title="Gallery"
              subtitle="Gallery accepts image files only."
            >
              <FilePicker
                label="Gallery Images"
                accept="image/png,image/jpeg,image/jpg,image/webp"
                multiple
                files={galleryFiles}
                onChange={setGalleryFiles}
                helperText="Accepted: PNG, JPG, JPEG, WEBP"
              />
            </SectionCard>

            <SectionCard
              title="Videos"
              subtitle="Videos accept file uploads only."
            >
              <FilePicker
                label="Video Files"
                accept="video/mp4,video/webm,video/quicktime"
                multiple
                files={videoFiles}
                onChange={setVideoFiles}
                helperText="Accepted: MP4, WEBM, MOV"
              />
            </SectionCard>

            <div className="flex flex-col-reverse gap-3 border-t border-neutral-100 pt-6 sm:flex-row sm:justify-end">
              <button
                type="button"
                onClick={handleClose}
                disabled={submitting}
                className="inline-flex h-12 items-center justify-center rounded-2xl border border-neutral-200 bg-white px-5 text-sm font-semibold text-black transition hover:border-black disabled:opacity-60"
              >
                Cancel
              </button>

              <button
                type="submit"
                disabled={submitting}
                className="inline-flex h-12 items-center justify-center rounded-2xl bg-black px-5 text-sm font-semibold text-white transition hover:opacity-90 disabled:opacity-60"
              >
                {submitting ? "Saving..." : "Save Property"}
              </button>
            </div>
          </form>
        </FormProvider>
      </div>
    </div>
  );
}